// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DigitalMenuApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace DigitalMenuApi.Data
{
    public class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> entity)
        {
            entity.HasIndex(e => e.RoleId);

            entity.HasIndex(e => e.StoreId);

            entity.Property(e => e.IsAvailable)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.Password).IsUnicode(false);

            entity.Property(e => e.Username)
                .IsRequired()
                .IsUnicode(false);

            entity.HasOne(d => d.Role)
                .WithMany(p => p.Account)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Account_AcountRole");

            entity.HasOne(d => d.Store)
                .WithMany(p => p.Account)
                .HasForeignKey(d => d.StoreId)
                .HasConstraintName("FK_Account_Store");
        }
    }
}
