// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DigitalMenuApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace DigitalMenuApi.Data
{
    public class ProductListConfiguration : IEntityTypeConfiguration<ProductList>
    {
        public void Configure(EntityTypeBuilder<ProductList> entity)
        {
            entity.HasOne(d => d.Box)
                .WithMany(p => p.ProductList)
                .HasForeignKey(d => d.BoxId)
                .HasConstraintName("FK_ProductList_Box");
        }
    }
}
