// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DigitalMenuApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace DigitalMenuApi.Data
{
    public class ProductListProductConfiguration : IEntityTypeConfiguration<ProductListProduct>
    {
        public void Configure(EntityTypeBuilder<ProductListProduct> entity)
        {
            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductListProduct)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductListProduct_Product");

            entity.HasOne(d => d.ProductList)
                .WithMany(p => p.ProductListProduct)
                .HasForeignKey(d => d.ProductListId)
                .HasConstraintName("FK_ProductListProduct_ProductList");
        }
    }
}
