// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DigitalMenuApi.Models
{
    public partial class ProductListProduct
    {
        public int Id { get; set; }
        public int? ProductListId { get; set; }
        public int? ProductId { get; set; }
        public int? Location { get; set; }

        public virtual Product Product { get; set; }
        public virtual ProductList ProductList { get; set; }
    }
}