// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DigitalMenuApi.Models
{
    public partial class ScreenTemplate
    {
        public int ScreenId { get; set; }
        public int TemplateId { get; set; }
        public int Id { get; set; }

        public virtual Screen Screen { get; set; }
        public virtual Template Template { get; set; }
    }
}