// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DigitalMenuApi.Models
{
    public partial class Session
    {
        public Session()
        {
            BoxFooter = new HashSet<Box>();
            BoxHeader = new HashSet<Box>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Src { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Box> BoxFooter { get; set; }
        public virtual ICollection<Box> BoxHeader { get; set; }
    }
}